var lista=["maçã", "pera", "limão", "laranja"];
console.log(lista);
console.log(lista[1]);
alert(lista[1]); 
lista.push("uva");
console.log(lista);
console.log(lista.length);
console.log(lista.reverse());
console.log(lista.toString());
console.log(lista.toString()[1]);
